[package]
name = "pickit"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
crossterm = "0.27.0"
ratatui = "0.25.0"
thiserror = "1.0.58"

[dev-dependencies]
tempfile = "3.10.1"
