[package]
name = "pickit"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
ratatui = "0.30.0"
thiserror = "2.0.17"

[dev-dependencies]
tempfile = "3.24.0"
